### ISSUE TITLE
java logging statements 

### ISSUE THREAD

**Issue by cvignola** [kappnav/issues#103]
We need logging in the API server.   There should be a simple switch,  implemented as a static variable and a log method that allows classification of trace level.

E.g. enum LOG_LEVEL = { NONE, ENTRY, EXIT, ERROR, INFO, DEBUG, ALL } 

Note: default log level is INFO.

A separate issue will be created to establish a user-facing external that enables trace to be dynamically enabled/disabled

**Comment by juniartisu** [comment]
Changes done using the following PRs:
- https://github.com/kappnav/apis/pull/43
- https://github.com/kappnav/apis/pull/45
- https://github.com/kappnav/apis/pull/46 
- https://github.com/kappnav/apis/pull/47
