### ISSUE TITLE
logging dynamic switch

### ISSUE THREAD

**Issue by cvignola** [kappnav/issues#104]
In support of https://github.com/kappnav/Issues/issues/103 we need a way for an end user to dynamically enable/disable tracing in kappnav components.  The initial support will be for the api server.  It may be eventually extended to support other kappnav components.  

The basic idea is to support new fields the kappnav CR:

logging:
     apis:  {loglevel}
     {future}:  {loglevel} 

trace string is 'none', 'all',  'entry', 'info', 'error', 'debug', 'warning'

note: 'none' is default. 

e.g. 

logging: 
    apis:  none 

logging:
    apis: all

**operation** 
 
The kappnav controller will monitor the trace field and respond to change by calling a new API on the API server to set the new trace value.  This issue will also deliver this new API.

**Comment by rlcundiff** [comment]
I'll start on this while Amy is away.

**Comment by amylin1** [comment]
Create a custom resource watcher in apis to monitor any kappnav CR is installed/updated with logging info.
