### ISSUE TITLE
UI action performance very slow in some cases

### ISSUE THREAD

**Issue by cvignola** [kappnav/issues#105]
Best example of this problem is 'view kibana logs' for liberty subkind.  See stocktrader application.  The default action simply displays a webpage of instructions from github.com.  However, the page takes nearly 60 seconds to load when the action is selected from kAppNav.  This page loads immediately when accessed from a browser.   Why does it launch so slowly from the kAppNav UI ?

**Comment by cvignola** [comment]
Note, this problem is not present on okd.  It was originally observed on ocp.  However,  we are lacking a working ocp cluster at the present time.  I will close this issue until I can reproduce on ocp with latest code.

**Comment by mrglavas** [comment]
https://github.com/kappnav/issues/issues/111 is the likely root cause of the performance issues on OCP with resolving actions.
