### ISSUE TITLE
make log access easy on command action UI page

### ISSUE THREAD

**Issue by cvignola** [kappnav/Issues#11]
Right now, you have to click into the command action detail, which takes you to the job detail page.  From there, you can access the log.  The log should be available directly from the command action page. 

Add toaster popup to display command results.  Link to the logs will be on that toaster.

We will need a new action to return the job log URL to the UI . See https://github.com/kappnav/Issues/issues/67

**Comment by k8vance88** [comment]
After investigating further, the UI is not returned the action-map for 'resource/commands' api. The jobs list we get is:
![image](https://user-images.githubusercontent.com/29546393/69178884-2052e400-0ad0-11ea-938e-8f6879ad5dea.png)

From applications you can see we are given the action-map:
![image](https://user-images.githubusercontent.com/29546393/69178871-1a5d0300-0ad0-11ea-8d2b-15521c7b9374.png)


@cvignola an api change to 'resource/commands' to return the action-map will fix this issue.

**Comment by cvignola** [comment]
action-map return to be delivered by issue #92
