### ISSUE TITLE
UI not honoring enablement-label/enablement-annotation in action config maps

### ISSUE THREAD

**Issue by cvignola** [kappnav/issues#112]
e.g. stocktrader liberty deployments display in their action menus 

- view 1.1 metrics 
- view 2.0 metrics 
- view project doc
- view project source
- etc

However, none of the required labels or annotations are specified on any of the deployments. Therefore they should not be displayed.

**Comment by k8vance88** [comment]
Exposed by https://github.com/kappnav/ui/pull/86.  I will fix this by putting the kappnav constants in the main constants file and only extensions will go in the extension file.  Original cause was having the duplicated constants file and not keeping them in sync.
