### ISSUE TITLE
Migrate away from carbon-addons-cloud node module

### ISSUE THREAD

**Issue by kinueng** [kappnav/issues#123]
Related to https://github.com/kappnav/issues/issues/118

The `carbon-addons-cloud` node module is now deprecated.  See https://github.com/carbon-design-system/carbon-addons-cloud/commit/7fa5ccad4148a62606e1521375ad1dbf15a0120d.

We need to evaluate what we need to do to remove the `carbon-addons-cloud` node module from our dependencies.

**Comment by k8vance88** [comment]
This will be taken care of by the facelift
