### ISSUE TITLE
UI Applications view without applications show horizontal scroll bar

### ISSUE THREAD

**Issue by k8vance88** [kappnav/issues#141]
![image](https://user-images.githubusercontent.com/29546393/74863021-cce07400-5312-11ea-9995-e8764d9aef9d.png)

**Comment by erica-banda-03** [comment]
In the image I also noticed that the right border of the empty row is gone. This is due to the colSpan being set to the incorrect value. I'll be fixing the scrollbar and right border issue under the same PR.

**Comment by erica-banda-03** [comment]
Fixed with: https://github.com/kappnav/ui/pull/124
