### ISSUE TITLE
Sync Openshift and kAppNav apps 

### ISSUE THREAD

**Issue by cvignola** [kappnav/issues#142]
Openshift has an application composition model based on the "partof" label.  The kappnav model is based on the Application CRD.  The goal of this issue is to automatically make applications created using the Openshift model visible and operable in the kappnav UI.

**Comment by mrglavas** [comment]
See: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels for description of **app.kubernetes.io/part-of**. Also: https://docs.openshift.com/container-platform/4.3/applications/application_life_cycle_management/odc-viewing-application-composition-using-topology-view.html for how **part-of** is used in the OpenShift Toplogy View.

**Comment by mrglavas** [comment]
An auto-creation/deletion scenario that should be considered in the design: https://github.com/kappnav/issues/issues/157.

**Comment by cvignola** [comment]
dup of #122
