### ISSUE TITLE
update oauth-proxy config to skip sign-in pop-up window

### ISSUE THREAD

**Issue by arunavemulapalli** [kappnav/issues#143]
background : 

AppNavigator UI  is protected by OpenShift OAuth server via OAuth proxy.  Current configuration always display the sign-in page "Log in with Open Shift" before reaching the OAuth login page. Since "login with OAuth" is the only option, we should skip this pop-up window, and go directly to the OAuth login page.  Skipping the sign-in page is useful for SSO, if OpenShift OAuth server is configured to use one SSO server (like IBM ID, or google), user could securely access the UI silently without clicking the button.

Jim and Chunlong have investigated and tested various SSO scenarios for platform applications, and believe that we should get rid of this unnecessary button (to avoid the click). Could you please update the oauth proxy configuration to skip this? 

To skip the button, you can add the following property in the oauth-proxy configuration. 
skip-provider-button=true  (will skip sign-in-page to directly reach the next step: oauth/start)

**Comment by k8vance88** [comment]
The code that creates the oauth proxy container is here:  https://github.com/kappnav/operator/blob/master/pkg/utils/utils.go

May need to update createOAuthProxyArgs()

**Comment by k8vance88** [comment]
It's not as simple as adding the line to skip the button.  Skipping the button breaks the logout flow.  I haven't yet found a solution to logout that doesn't use the oauth/sign_in url.  I have looked at what the openshift console does, however, I don't know if their flow would work for our application as we are using a service account.

**Comment by k8vance88** [comment]
I have tested the logout button without the skip button and it isn't working as it should.  I will use this work item to skip the button and hide the logout button (temporarily) until we can get another logout action in place.
