### ISSUE TITLE
Add a label to all ConfigMaps to identify its association with kAppNav.

### ISSUE THREAD

**Issue by mrglavas** [kappnav/issues#151]
**Problem:** kAppNav uses ConfigMaps for built-in configuration and for definition of actions, sections and status mapping. ConfigMaps exist for many other components in Kubernetes and are used by other applications. With recent design changes (e.g. to action maps) there is no longer a known pattern to the naming of kAppNav's maps and that makes it difficult to distinguish which maps are associated with kAppNav from all of the other ConfigMaps in the system. The API server has started to watch ConfigMaps in order to cache them and needs a reliable way to monitor the set of ConfigMaps that apply to kAppNav.

**Solution**: Add a label to ConfigMaps associated with kAppNav, providing a reliable way to watch and query for these specific types of maps.

Proposed label name `kappnav.io/map-type` with the following values:
- `builtin` _(for kAppNav built-in maps, such as: builtin and kappnav-config)_
- `action`
- `sections`
- `status`

The kAppNav operator should add these labels to all ConfigMaps that it creates and owns. ConfigMaps that have been contributed by and are owned by another party are responsible for adding the label to the map. The API server and other consumers may want to validate that these labels are present when they process one of these maps and report a warning/error if they are missing.

The API server should update its ConfigMap cache to watch for all maps that have a `kappnav.io/map-type` label. This can be achieved with a selector with a match expression that tests for the existence of the label. This will limit the watch events reported back from the Kube API to only those relevant to kAppNav which is good for performance and better precision on invalidation of the cache when a (rare) change to a ConfigMap occurs.

**Comment by cvignola** [comment]
Proposal looks good.  Only thing to guard against is the API writing too many messages about missing labels.  I.e. don't want forever watch loop printing those messages over and over and over !  :)

**Comment by mrglavas** [comment]
Yes, agreed about the volume of messages in the log.

**Comment by mrglavas** [comment]
Should deliver before or at the same time as: https://github.com/kappnav/issues/issues/100 so that the scope of the watch for ConfigMaps is correct.

**Comment by cvignola** [comment]
Tests in operator: 

Operator adds our label to all configmaps it creates. 

Tests in API server (test each in 1) kappnav namespace and in 2) another namespace - 8 tests total) 

1) configmap with label does not print warning 
2) configmap without our label DOES print warning
3) action configmap with our label gets cached (validate existing code - Susan's - still work) 
4) when our action configmap with our label causes cache eviction

**Comment by juniartisu** [comment]
Operator codes changes in  https://github.com/kappnav/operator/pull/92 and https://github.com/kappnav/operator/pull/94
Apis code changes in https://github.com/kappnav/apis/pull/73
