### ISSUE TITLE
Eliminate spurious "reconciled" message in operator log

### ISSUE THREAD

**Issue by cvignola** [kappnav/issues#163]
The operators writes 100's and 100's of messages like this one - e.g.

```
{"level":"info","ts":1584643649.9269834,"logger":"utils","msg":"Reconciled","Kind":"Service","Name":"kappnav-ui-service","Status":"updated"}
```

There should be no where near so many of these messages.

**Comment by cvignola** [comment]
See also https://github.com/kappnav/issues/issues/135

**Comment by amylin1** [comment]
I have fixed the infinite reconciled messages on changing service account and UI service (status: updated) under issue#135, but we still see the repeatedly reconciled messages on updating UI and controller deployment.  I have attempted to fix it in operator code and it works, but Michael concerned that the it may cause some side effect (i.e. someone manually change deployment via kubectl apply command).   So I will leave UI and controller deployment code unchanged which means we will continue to see repeatedly reconciled messages on updating UI/controller deployment. 

I also confirmed with Artur that it is normal to see many reconciled messages (status: created /unchanged ..) as it will appear every time Reconcile method is called and open shift (ocp) itself will change some resources such as it inserts its own annotations and adds ClusterIP field, etc.

**Comment by mrglavas** [comment]
To be clear, there were side effects to changing the operator code for the deployments in the way that it would have been changed, including config from the kAppNav CR (e.g. pull policy and memory/CPU constraints) not being applied by the operator to the deployments. If we discover in the future that there's something to improve there, we would need a better solution which responds to config changes and maintains the containers in the desired state.

**Comment by amylin1** [comment]
Yes, we can investigate it more later to see if we can find a better solution to respond the container config change or keep the config somewhere instead of setting it every time (it looks like the updated reconcile message is triggered by pts.Spec.Containers change after further investigation).
