### ISSUE TITLE
UI server logging

### ISSUE THREAD

**Issue by cvignola** [kappnav/issues#165]
Add log statements, as per https://github.com/kappnav/design/blob/master/logging.md

**Comment by k8vance88** [comment]
The full scenario requires 2 work items (2 will be worked under #167 ): 
1. UI server to host a REST api to set the log level
2. API server to watch for level changes and call the UI server REST api like this:
POST http://localhost:3000/extensions/logLevel  with application/json payload 
{
  "level" : "debug"
}

with the following level substitutions:

Operator level         =>          UI REST api level to send
----------------------------------------------------
       none                             off  
       error                            error
       warning                          warn
       info                             info
       debug                            debug
       entry                            trace
       all                              all

For example, if the api server detects that the ui should be at log level entry, then it should call the UI server REST api with level 'trace'.
