### ISSUE TITLE
Logging external for UI logging

### ISSUE THREAD

**Issue by cvignola** [kappnav/issues#167]
as per design https://github.com/kappnav/design/blob/master/logging.md

**Comment by k8vance88** [comment]
API server to watch for level changes and call the UI server REST api like this:
POST http://localhost:3000/extensions/logLevel with application/json payload
{
"level" : "debug"
}
with the following level substitutions:

Operator level => UI REST api level to send
   none                             off  
   error                            error
   warning                          warn
   info                             info
   debug                            debug
   entry                            trace
   all                              all
For example, if the api server detects that the ui should be at log level entry, then it should call the UI server REST api with level 'trace'.

See #165 for UI server REST api.

**Comment by k8vance88** [comment]
Started working on the api work needed to set the trace level.  There might be more work needed for the kappnav CR to set the ui level.

**Comment by k8vance88** [comment]
See PR https://github.com/kappnav/apis/pull/78
