### ISSUE TITLE
Add kappnav.subkind annotation to appsody node.js stack

### ISSUE THREAD

**Issue by cvignola** [kappnav/issues#170]
PR this repo:  https://github.com/appsody/stacks/tree/master/incubator

value: 

annotations:
    kappnav.subkind: Nodejs

**Comment by juniartisu** [comment]
After discussion with Appsody team, turns out we do not need this issue at this moment.
So I am closing this issue now and for detail information/discussion can be seen in this PR
https://github.com/appsody/stacks/pull/762
