### ISSUE TITLE
Samples: legacyapp - Liberty/JBoss action config map contains invalid NLS fields.

### ISSUE THREAD

**Issue by mrglavas** [kappnav/issues#172]
The Liberty and JBoss action config maps in the legacyapp sample contains NLS fields that are not valid message keys. This causes the UI to display menu items with "!" around the intended text, for example "!View home page!". Not sure that we provided a way for extenders of kAppNav to provide their own NLS text. Suggesting that we remove those from the sample.

**Comment by cvignola** [comment]
If you remove them from the sample,  they actions are not displayed at all!   This will be fixed when we implement feature https://github.com/kappnav/issues/issues/191

**Comment by cvignola** [comment]
Fixed in https://github.com/kappnav/samples/pull/11
