### ISSUE TITLE
Samples: Installation of stock-trader partially fails because of hard-coded namespace in loyalty_actions.yaml.

### ISSUE THREAD

**Issue by mrglavas** [kappnav/issues#186]
Installing stock-trader using `kubectl create -f samples/stocktrader -n stocktrader` is currently producing the following error:
`
the namespace from the provided object "stock-trader" does not match the namespace "stocktrader". You must pass '--namespace=stock-trader' to perform this operation.`

Should remove the namespace field from the `loyalty_actions.yaml` config map.

**Comment by cvignola** [comment]
Ok, but must be reconciled with the way install.sh sets the namespace for each project.  See https://github.com/kappnav/samples/blob/master/install.sh, which uses value from a file named NAMESPACE in each project. E.g. https://github.com/kappnav/samples/blob/master/stocktrader/NAMESPACE

**Comment by mrglavas** [comment]
The value in that NAMESPACE file just happens to match the one in `loyalty_actions.yaml`, but our install instructions for stocktrader in the main kAppNav [README](https://github.com/kappnav/README) does not use install.sh. I didn't see a namespace field in any of the other YAML files when I checked them.

**Comment by cvignola** [comment]
Fixed by removing namespace: stock-trader from loyalty-level.
