### ISSUE TITLE
security issue reported in samples/music-service

### ISSUE THREAD

**Issue by cvignola** [kappnav/issues#193]
Goto https://github.com/kappnav/samples

See this: 

![image](https://user-images.githubusercontent.com/15363082/80743831-4c44ad80-8ae3-11ea-8ccc-e46e5e8bc344.png)

**Comment by amylin1** [comment]
Run "npm audit" and there are 4 vulnerability issues under api-namespace caused by "mocha" package version and 3 vulnerability issues under ui-namespace (also caused by mocha package version).   I have followed the instructions to fix them.  They are clean now after fixes.
