### ISSUE TITLE
0.6.1 Kabanero Test - kAppNav not recognizing app installed using doc

### ISSUE THREAD

**Issue by StringCheeseCR** [kappnav/issues#201]
I am working on migrating from Kabanero 0.6.1 to 0.9 and working on installing an App on Kabanero to make sure it still works after migrating.

I followed this doc...
https://kabanero.io/guides/using-kAppNav/#add-the-application-in-kappnav

I got the NodeJS app installed in the OpenShift Console. I then tried the procedure to link the app into the kAppNav dashboard and it never went beyond "Unknown"

Initially I thought it was I defined one of the resources as 'pod' instead of 'Pod' but even after editing and fixing that it didn't work. Chatting with Chris V it appears to be a bug as he was able to reproduce it.

**Comment by StringCheeseCR** [comment]
Listing from the ClusterServiceVersions

`kappnav                                                 appsody-operator.v0.3.0                      Appsody Operator                 0.3.0                 appsody-operator.v0.2.2                      Succeeded
kappnav                                                 elasticsearch-operator.4.3.19-202005041055   Elasticsearch Operator           4.3.19-202005041055   elasticsearch-operator.4.3.14-202004200457   Succeeded
kappnav                                                 jaeger-operator.v1.17.2                      Red Hat OpenShift Jaeger         1.17.2                                                             Succeeded
kappnav                                                 kiali-operator.v1.12.11                      Kiali Operator                   1.12.11               kiali-operator.v1.12.7                       Succeeded
kappnav                                                 openshift-pipelines-operator.v0.10.4         OpenShift Pipelines Operator     0.10.4                openshift-pipelines-operator.v0.9.1          Succeeded
kappnav                                                 serverless-operator.v1.4.1                   OpenShift Serverless Operator    1.4.1                 serverless-operator.v1.4.0                   Succeeded
kappnav                                                 servicemeshoperator.v1.0.8                   Red Hat OpenShift Service Mesh   1.0.8                 servicemeshoperator.v1.0.7                   Succeeded
`

**Comment by StringCheeseCR** [comment]
Yaml from the OCP dashboard for the app...

kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://github.com/sclorg/nodejs-ex.git'
    deployment.kubernetes.io/revision: '2'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"cjr-nodejs:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"cjr-nodejs\")].image"}]
  selfLink: /apis/apps/v1/namespaces/kappnav/deployments/cjr-nodejs
  resourceVersion: '6495081'
  name: cjr-nodejs
  uid: 180bc856-773b-4398-bbc0-0f7edcdd3ce7
  creationTimestamp: '2020-05-12T14:59:32Z'
  generation: 2
  namespace: kappnav
  labels:
    app: cjr-nodejs
    app.kubernetes.io/component: cjr-nodejs
    app.kubernetes.io/instance: cjr-nodejs
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: cjr-nodejs-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 10-SCL
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cjr-nodejs
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cjr-nodejs
        deploymentconfig: cjr-nodejs
    spec:
      containers:
        - name: cjr-nodejs
          image: >-
            image-registry.openshift-image-registry.svc:5000/kappnav/cjr-nodejs@sha256:cb9d501c91fc9c2e54b6479e61bbaabcc42c1c33f4e4973afb5a3572e959a181
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-05-12T15:01:14Z'
      lastTransitionTime: '2020-05-12T15:01:14Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-05-12T15:01:14Z'
      lastTransitionTime: '2020-05-12T14:59:33Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "cjr-nodejs-7d5674b5bc" has successfully progressed.

**Comment by StringCheeseCR** [comment]
If you want to log in...
https://console-openshift-console.apps.svtauto892067.os.fyre.ibm.com/k8s/ns/kappnav/deployments/cjr-nodejs/yaml
kubeadmin / HzGYQ-XK9UQ-N9ynI-ivN5z

**Comment by cvignola** [comment]
v1/Pod is missing from CORE_KIND_TO_API_VERSION_MAP in ComponentInfoRegistry.java

and user must specify group value for DeploymentConfig

**Comment by cvignola** [comment]
Fix by https://github.com/kappnav/apis/pull/100.  Will deliver into kAppNav 0.10.0
