### ISSUE TITLE
Fail to build UI with error from /app/node_modules/camelcase/index.js:69

### ISSUE THREAD

**Issue by juniartisu** [kappnav/issues#206]
/app/node_modules/camelcase/index.js:69
		.replace(/[_.\- ]+([\p{Alpha}\p{N}_]|$)/gu, (_, p1) => p1.toLocaleUpperCase())
		^
SyntaxError: Invalid regular expression: /[_.\- ]+([\p{Alpha}\p{N}_]|$)/: Invalid escape

**Comment by k8vance88** [comment]
This was caused by the assets-webpack-plugin releasing a new version 3.10.0, which uses a new version of camelcase 6.0.0.   Likely that library is not compatible with our version of node.

**Comment by k8vance88** [comment]
I opened this issue for camelcase: https://github.com/sindresorhus/camelcase/issues/70

**Comment by k8vance88** [comment]
In the meantime we will force our package.json to pull version 3.9.x.
