### ISSUE TITLE
KAppNav shows app as unknown status on unregistered component kind (i.e. Route)

### ISSUE THREAD

**Issue by amylin1** [kappnav/issues#211]
Refer to IBMCloudPak4Apps issue #738
https://github.ibm.com/IBMCloudPak4Apps/icpa-system-test/issues/738

**Comment by anneqm** [comment]
@amylin1 @rlcundiff any progress on this one?  Just checking prior to scrum of scrum call tomorrow.   Thanks!

**Comment by amylin1** [comment]
It is fixed and merged to kappnav already.
