### ISSUE TITLE
Fix linter errors that were suppressed with eslint-disable comments

### ISSUE THREAD

**Issue by erica-banda-03** [kappnav/issues#36]
Eslint was enabled in the `kappnav/ui directory` and changes were made to get rid of the linter errors. Some errors were not fixed since they required a better understanding of the code or more refactoring. Those errors were "suppressed" by using eslint-disable in the comments. Below are the notes of what errors still need to be fixed and what files they're in. 

**Files with error: Do not use Array index in key** (Search for // eslint-disable-next-line react/no-array-index-key)

- [x] actions\common.js
- [x] components\kappnav\common\ModalFormItems.js
- [x] components\kappnav\common\ModalListItem.js
- [ ] component\kappnav\common\StructuredListModules.js
- [x] components\kappnav\modals\ActionModal.js
- [x] components\kappnav\modals\NavModal.js
- [x] components\kappnav\modals\ResourceModal.js

**Files with error: prop_name is missing in props validation.** (Search for // eslint-disable-next-line react/prop-types)

- [ ] components\kappnav\common\ModalListItem.js
- [ ] components\kappnav\common\SecondaryHeader.jsx
- [ ] components\kappnav\modals\ActionModal.js
- [ ] components\kappnav\modals\NavModal.js

**Files with error: Use callback in setState when referencing the previous state.** (Search for // eslint-disable-next-line react/no-access-state-in-setstate)

- [ ] components\kappnav\common\SecondaryHeader.jsx
- [ ] component\kappnav\common\StructuredListModules.js
- [ ] components\kappnav\modals\ActionModal.js
- [ ] components\kappnav\modals\NavModal.js
- [ ] components\kappnav\modals\ResourceModal.js
- [ ] components\AppView.js
- [ ] components\ComponentView.js

**Files with error message related to unused vars** (Search for comments with react/no-unused-state or react/no-unused-vars)
- [ ] components\kappnav\modals\RemoveResourceModal.js
- [ ] components\ComponentView.jsx
- [ ] server\health.js

**Files with error: Do not use setState in componentDidMount** (Search for // eslint-disable-next-line react/no-did-mount-set-state)
- [ ] components\kappnav\modals\RemoveResourceModal.js

Other:
-  eslint-disable-next-line import/no-named-as-default is needed when React + Redux is used according to this article: https://stackoverflow.com/questions/44437203/how-do-i-resolve-eslint-import-no-named-as-default
- in components\DetailView.jsx: there are a few // eslint-disable-next-line no-undef comments since I didn’t know the proper way to define url and resourceTypes

**Comment by rlcundiff** [comment]
It's unnecessary to update code that's about to be obsoleted by #155 .
