### ISSUE TITLE
UX Design update for Website including Kabanero

### ISSUE THREAD

**Issue by pgnyeste** [kappnav/Issues#40]
1.) Update kAppNav website to link to Kabanero.io
2.) Update middle section with description to better reflect kAppNav's extension to Kubernetes with visual examples/illustrations

I'll add a mockup

**Comment by cvignola** [comment]
Mockup:  

![image](https://user-images.githubusercontent.com/15363082/66342300-ba8b0e00-e90e-11e9-935a-ca3efc478cf6.png)

Note: text and yaml example are not final.

**Comment by pgnyeste** [comment]
![kAppNav Website v1 0 (October)](https://user-images.githubusercontent.com/51239735/66342689-068e8080-e918-11e9-96d6-3777cd617942.png)

**Comment by DoloresLopez** [comment]
@erica-banda-03 is this issue done?  Can it be closed?
