### ISSUE TITLE
Add google analytics to kappnav.io

### ISSUE THREAD

**Issue by cvignola** [kappnav/Issues#41]

**Comment by kinueng** [comment]
# Checklist

- [ ] Create google analytics (GA) account
- [ ] Create google tag manager (GTM) account
- [ ] Turn on IP Anonymization in Analytics for GDPR https://support.google.com/analytics/answer/2763052?hl=en

- [ ] Create 1 tag to measure visitors to kappnav.io

- [ ] Create 1 tag to measure visitor who leave kappnav.io by clicking on any "outbound" link on kappnav.io

- [ ] Create a GA filter to remove any traffic data from localhost.  Localhost data is recorded from my testing of the website on my local machine via localhost:4000 (aka `jekyll serve`)
