### ISSUE TITLE
Support OCP 4.2

### ISSUE THREAD

**Issue by barecode** [kappnav/issues#46]
This is a requirement from Kabanero:
https://github.com/kabanero-io/roadmap/issues/100

**Comment by juniartisu** [comment]
Juniartis-MacBook-Pro:prism jasuryak$ oc get nodes
NAME                              STATUS   ROLES           AGE    VERSION
master0.kappnav.os.fyre.ibm.com   Ready    master,worker   143m   v1.14.6+c07e432da
master1.kappnav.os.fyre.ibm.com   Ready    master,worker   144m   v1.14.6+c07e432da
master2.kappnav.os.fyre.ibm.com   Ready    master,worker   143m   v1.14.6+c07e432da
worker0.kappnav.os.fyre.ibm.com   Ready    worker          144m   v1.14.6+c07e432da
worker1.kappnav.os.fyre.ibm.com   Ready    worker          144m   v1.14.6+c07e432da
worker2.kappnav.os.fyre.ibm.com   Ready    worker          143m   v1.14.6+c07e432da

**Comment by juniartisu** [comment]
Configured OCPV4.2 with 3 master nodes and 3 worker nodes.

**Comment by cvignola** [comment]
done.
