### ISSUE TITLE
UI: Provide a pointer to the Install Samples flow when kAppNav has no apps

### ISSUE THREAD

**Issue by barecode** [kappnav/issues#49]
As part of the initial user experience, I would like to make sure users know that kAppNav needs some kind of App CRD in their environment in order to appropriately render apps. That is not really clear right now. As part of the "easiest" thing to do, we could create a little pop-up in the when no apps are present and point them back to the Install Samples step of the install instructions (done directly in the UI) so that users who get into a blank landscape beause there are no apps have a clear next step.

Future we could try and detect if apps exist which need an App CRD created, and I'll open that as a sepearte item.

**Comment by cvignola** [comment]
When there are no apps, no cells, no collectives, the UI was update to launch the create app, cell or collective dialog
