### ISSUE TITLE
Drop down details for application row in UI

### ISSUE THREAD

**Issue by cvignola** [kappnav/issues#56]
Goals: 

1. support potentially multiple 'detail' sections.
1. support multiple sources of data for each detail section (one source for each section) 
1. make it possible for external projects to dynamically register section/source/actions

MVP:  support section kind with data from specified labels/annotations and static registration

Mock-up of idea as seen in UI: 

![image](https://user-images.githubusercontent.com/15363082/67117028-46225b80-f1a7-11e9-830f-412ae7284803.png)

![image](https://user-images.githubusercontent.com/15363082/67118909-88e63280-f1ab-11e9-8c32-40272f1f3703.png)

**Comment by kinueng** [comment]
Here is how you enable expandable/collapsable rows in the table
http://v6-react.carbondesignsystem.com/?selectedKind=DataTable&selectedStory=with%20expansion&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

**Comment by amylin1** [comment]
Will use this issue for APIs support on drop down section and section-data details

**Comment by amylin1** [comment]
The design details including example:
https://github.ibm.com/WASCloudTribe/design/blob/master/prism/ui-detail-sections.md

**Comment by pgnyeste** [comment]
Based on these Label:Values.
`appsody.git.repo: http://github.com/myproject`
`appsody.git.commit: 33ff448d`
`appsody.stack.configured: open-liberty.v1.0.0`

Some ideas to make it more human readable and ordered by Hierarchy of Stack => Repo => Commit info:
![image](https://user-images.githubusercontent.com/51239735/67983948-21dd6a80-fbfc-11e9-8036-203b997d7272.png)

Ultimately, the idea would be to surface the most important aspects to the user.  Best guess here is Stack where the project came from, Git Repo it is in, and last commit.

Other Label:Value pairs (which I'm sure could be many!) could be hidden but still easily used and copyable in a potential dialog box especially those that we haven't had time to parse or make as human readable.

**Comment by k8vance88** [comment]
UI PRs: https://github.com/kappnav/ui/pull/59, https://github.com/kappnav/ui/pull/62 & https://github.com/kappnav/ui/pull/63

**Comment by pgnyeste** [comment]
Latest design for enhancing the UX of Application Details and thus appsody information:
https://ibm.invisionapp.com/share/PWNZHCO6YJD

Show and Hide are used to view or collapse the extra information which will contain tooltips and links for more information beyond the Stack, Source, and Commit info
