### ISSUE TITLE
substitution resolver API must return error data when substitution fails 

### ISSUE THREAD

**Issue by cvignola** [kappnav/Issues#7]
Must return error for any ${} operator failure.  Design here:  https://github.ibm.com/WASCloudTribe/design/blob/master/prism/APIs.md#error-return

more detail: 

The pattern resolver API accepts the value of an action config map url-pattern or cmd-pattern string.  These strings contain substitutions symbols as per the design in https://github.ibm.com/WASCloudTribe/design/blob/master/prism/actions-config-maps.md#config-action-patterns

These patterns can employ substitution operators (e.g. ${<operator>}) to substitute values into the pattern at time of use. 

e.g. 

```
 "url-pattern":"${snippet.create_kibana_log_url(${builtin.kibana-url},${func.podlist(${resource.$.metadata.namespace},${resource.$.metadata.name})})}"
```

As you can see in the example,  the substitution operator can contain nested substitutions.  The operators are resolved from the inside out - meaning the inner operators are resolved first, and then resolution works its way from inner-most to out-most until all operators are resolved. 

The problem is it is very hard to develop and debug these patterns.  The reason why is because with the existing API, if there is any problem resolving any substitution operator,  the resolution stops and the original pattern is returned.  This gives you no idea what is wrong.  

We need to improve this by updating the API to return an error indicating where in the pattern resolution processing, the error was found and what the problem is.  

In the case of the ${snippet} operator, which executes a piece of javascript,  the error from the node.js interpreter (called by the API implementation) must be returned, so the developer knows what the error was inside the javascript itself.

**Comment by amylin1** [comment]
Closed it accidentally, so reopen it
