### ISSUE TITLE
UI use new job log API action

### ISSUE THREAD

**Issue by cvignola** [kappnav/issues#80]
See #67

**Comment by cvignola** [comment]
dup of #11

**Comment by k8vance88** [comment]
I tested this and did not see the job log url action. More investigation needed.

**Comment by k8vance88** [comment]
After investigating further, the UI is not returned the action-map for 'resource/commands' api. The jobs list we get is:
![image](https://user-images.githubusercontent.com/29546393/69178600-8b4feb00-0acf-11ea-931b-08f185615aed.png)
From applications you can see we are given the action-map:
![image](https://user-images.githubusercontent.com/29546393/69178664-a9b5e680-0acf-11ea-87b9-c76f0d9ed5b6.png)

@cvignola an api change to 'resource/commands' to return the action-map will fix this issue.
