### ISSUE TITLE
package API server up as container for developer use

### ISSUE THREAD

**Issue by cvignola** [kappnav/issues#82]
1) docker file
2) install yaml 
3) script to install and open web page to route

**Comment by cvignola** [comment]
script details:

1. test if kubectl attached to kubernetes cluster - exit with error if not 
1. display info about current kubernetes cluster 
1. test if actdev installed 
1. if not installed, install actdev to actdev namespace 
1. wait for actdev and open it

**Comment by juniartisu** [comment]
Done using https://github.com/kappnav/apis/pull/25

**Comment by cvignola** [comment]
shipped.  see apis/tools
