### ISSUE TITLE
kappnav-controller pod fail to start, showed as CrashLookBackOff on minikube 1.16.2

### ISSUE THREAD

**Issue by juniartisu** [kappnav/issues#85]
kappnav-controller pod showed this error below:
I1115 01:18:44.129154       1 main.go:81] starting kappnav status controler inside cluster
I1115 01:18:44.140275       1 controller.go:549] Using core kind Service with: group:   version: v1  plural: services  namespaced: true
I1115 01:18:44.140299       1 controller.go:550]      instead of Service with: group:   version: v1  plural: services  namespaced: true
I1115 01:18:44.156333       1 controller.go:703] new startWatch kind: CustomResourceDefinition GVR: apiextensions.k8s.io/v1, Resource=customresourcedefinitions
I1115 01:18:44.156361       1 controller.go:704]      group: apiextensions.k8s.io  version: v1  resource: customresourcedefinitions
I1115 01:18:44.156507       1 batch_store.go:268] batchStore.run started
panic: interface conversion: interface {} is nil, not string
goroutine 91 [running]:
main.getCRDGVRKindSubresource(0xc000275060, 0xc0001b55e8, 0x408c01, 0x8, 0xc00029d3b0, 0xe826f5, 0x0, 0x0, 0xc00029d6d0, 0xc000516ed0, ...)
    /go/src/github.com/kappnav/controller/controller.go:1083 +0x377
main.(*ClusterWatcher).addKind(0xc0002715e0, 0x115dce0, 0xc000275060, 0x115dce0, 0xc000275060)
    /go/src/github.com/kappnav/controller/controller.go:1102 +0x6e
main.glob..func4(0xc0002715e0, 0xc000468e60, 0xc00026f0e0, 0x18, 0xc0002cabf0)
    /go/src/github.com/kappnav/controller/crd_handler.go:36 +0xb8
main.(*HandlerManager).callHandlers(0xc00028fd40, 0xc000040b60, 0x18, 0xc0002715e0, 0xc000468e60, 0xc00026f0e0, 0x0, 0x1b505c0)
    /go/src/github.com/kappnav/controller/handler_manager.go:92 +0x3d5
main.processNextItem(0xc0002715e0, 0xc000468e60, 0xc00029d700)
    /go/src/github.com/kappnav/controller/controller.go:445 +0x206
main.(*ClusterWatcher).startWatch.func4(0xc000468e60, 0xc0002715e0)
    /go/src/github.com/kappnav/controller/controller.go:777 +0x50
created by main.(*ClusterWatcher).startWatch
    /go/src/github.com/kappnav/controller/controller.go:773 +0x764

minikube dashboard showed as below:
<img width="1211" alt="Screen Shot 2019-11-14 at 7 15 17 PM" src="https://user-images.githubusercontent.com/28314552/68915832-402d8500-0729-11ea-802b-18db2cc6078d.png">

Here is my minikube env:
minikube v1.5.2 on Darwin 10.15
:cd:  Downloading VM boot image ...
   > minikube-v1.5.1.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
   > minikube-v1.5.1.iso: 143.76 MiB / 143.76 MiB [-] 100.00% 6.93 MiB p/s 21s
:fire:  Creating virtualbox VM (CPUs=4, Memory=8192MB, Disk=20000MB) ...
:whale:  Preparing Kubernetes v1.16.2 on Docker ‘18.09.9’ ...
:floppy_disk:  Downloading kubeadm v1.16.2
:floppy_disk:  Downloading kubelet v1.16.2

After hitting the above issue. I uninstalled kappnav and then delete kappnav namespace and install again but then got hung on kappnav-pre-delete pod and log showed as below:
/opt/app-src/root
total 8 drwxr-xr-x 2 node root 4096 Nov 1 15:15 . drwxr-xr-x 3 root root 4096 Nov 1 15:15 ..
DEBUG: KUBE_ENV=minikube
DEBUG: HOOK_MODE=predelete
use minikube file list
apply builtin.yaml
error: unable to recognize “/initfiles/builtin.yaml”: Unauthorized
apply service.ui.minikube.yaml
error: unable to recognize “/initfiles/service.ui.minikube.yaml”: Unauthorized
apply dummy.secret.yaml
error: unable to recognize “/initfiles/dummy.secret.yaml”: Unauthorized

**Comment by cvignola** [comment]
Default kubernetes version on minikube 1.5.2 is 1.16.2.  There is a binary incompatibility between 1.16 and earlier Kubernetes.  It appears the controller needs to be rebuilt with newer libraries.

OCP 4.2 uses Kubernetes 1.14.x

I ran the latest kappnav develop branch build on minikube 1.5.2/kubernetes 1.14.9 and it ran fine.  You can choose your kubernetes version level when you start minikube this way: 

```
minikube start --kubernetes-version='v1.14.9'
```
