### ISSUE TITLE
Create "developer mode" in API server that turns off config map caching

### ISSUE THREAD

**Issue by cvignola** [kappnav/issues#96]
Currently when running actdev tool (which runs API server alone in a container) the API server caches the config maps it reads. This makes it impossible to do round-trip development of action patterns.  We need to run this copy of the API with caching turned off.  This issue will implement an env var to turn off caching.  The actdev.yaml will set this env var.

**Comment by juniartisu** [comment]
https://github.com/kappnav/apis/pull/34

**Comment by mrglavas** [comment]
@cvignola @juniartisu There is no long term persistence of config maps in the API. The caching was designed to be local to the request, so that it doesn't fetch the same map multiple times while resolving the same expression. Was this tested or this is just an assumption?

**Comment by cvignola** [comment]
@mrglavas Ok, so you're saying the cache does not exist for the life of the APIs server process, but rather just for the life of a ResolutionContext instance,  which are created for each resolution request.  I looked at the code again, and yes, now I see that.  I mistook the helm operator's design for overwriting configmap updates with the original configmaps with the API server doing long-lived caching.  With the new operator this should no longer be an issue.  Thanks

**Comment by juniartisu** [comment]
Undo the changes to this in https://github.com/kappnav/apis/pull/37 as this issue is not needed anymore.
