### ISSUE TITLE
API server caching support 

### ISSUE THREAD

**Issue by cvignola** [kappnav/issues#98]
We need a long-lived cache in the API server to improve UI performance.  This cache needs to be invalidated upon update. E.g. cache configmaps.  Invalidate cache entry when/if configmap is updated.

Need to cache:

1. action config maps 
2. status config maps 
3. section config maps 
4. application/component lists 
5. application/component status

**Comment by mrglavas** [comment]
Delivered for 0.6.0:
- /application API
-- getApplication() uses application cache to return an application.
-- create/replace/delete update a "mod count" to immediately invalidate cached lists.
-- when the application is found in the cache no Kube API calls are generated.
- /applications API
-- uses cached list of all applications in cluster. Returns cached applications from each API method.
-- uses cached config maps for computing action and status config maps.
-- in the best case no Kube API calls are made for this kAppNav REST API.
- /components API
-- uses application cache to fetch the application object
-- no caching of component lists (yet)
-- uses cached config maps for computing action and status config maps.
-- in the best case Kube API calls limited to computation of the component list; one call for each component kind.
- /configmap API
-- kappnav-config map is frequently accessed by the UI and is served up from the config map cache.
- /resource (Action) API
-- uses cached config maps for computing the action config maps and for accessing other config maps that may be referenced by the pattern expression.
-- the Docker container was patched to allow "kubectl get" to cache results.
-- in the best case only one Kube API call is made to fetch the addressed resource.
- /status API
-- uses cached config maps for computing the status config maps.
-- in the best case only one Kube API call is made to fetch the addressed resource.

The application and config map caches are maintained using the Kubernetes watch API. application.rest.v1.Watcher provides the main watch loop for these caches. This utility is also used for monitoring the logging configuration in the kAppNav CR.

**Comment by mrglavas** [comment]
Follow up work:
- https://github.com/kappnav/issues/issues/136 - API Server: Allow watches to resume more gracefully.
- https://github.com/kappnav/issues/issues/137 - API Server: Investigate / implement caching of component lists
